// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentAppCore.Entity.StudentManagement.Entity
{
    public partial class Student_Registration
    {     
        [Key]
        public int Reg_Id { get; set; }
        [Required]
        [StringLength(15)]
        public string Register_Name { get; set; }
        [Required]
        [StringLength(15)]
        public string Password { get; set; }
        public bool Is_Teacher { get; set; }
        public bool Is_Delated { get; set; }
        [Column(TypeName = "date")]
        public DateTime Created_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }

        [InverseProperty("Reg_")]
        public virtual ICollection<Student_Mark_List> Student_Mark_List { get; set; }
    }
}